[package]
name = "bemudjo_server_telnet"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "bemudjo_server_telnet"
path = "src/main.rs"

[dependencies]
tokio.workspace = true